Migrated from setup to pyproject tom, inbluding pypi publishing script

diff --git a/scripts/pypi::publish b/scripts/pypi::publish
--- a/scripts/pypi::publish
+++ b/scripts/pypi::publish
@@ -12,12 +12,7 @@
 #  * Your cwd is the root of the package you want to publish.
 #  * You're using setuptools_scm to manage your version number, under git tags.
 #  * build dir is dist
-#
-#
-#  This setup aims to reduce the tasteless repetition of things such the verison number (from __version__, setup.cf, setup.py, pyproject.toml, git). But it does't do away with allo of you. You will need:
-#   * __version__.py:  should be in your scm and tagged at any rate.
-#   * either setup.py or setup.cfg:
-#  The script requires both versions to match, and will prompt you to confirm the version before publishing.
+#  * Uses pyproject.toml, with the version in __version__.py
 
 print_error() {
   echo -e "\033[31m$1\033[0m"
@@ -28,42 +23,18 @@ print_success() {
 }
 
 get_version() {
-  # get the package name
-  package_name=$(grep -E '^name\s*=' setup.cfg | cut -d "=" -f2 | xargs)
-  if [[ -z "$package_name" ]]; then
-    print_error "Could not determine package name from setup.cfg."
-    exit 1
-  fi
-  echo "Package name: $package_name"
+  package_name=$1
+  version=$(python -c "import importlib.util; spec = importlib.util.spec_from_file_location('$package_name.__version__', '$package_name/__version__.py'); module = importlib.util.module_from_spec(spec); spec.loader.exec_module(module); print(module.__version__)")
+}
 
-  # get version from setup.cfg
-  version=$(grep -E '^version\s*=' setup.cfg | cut -d "=" -f2 | xargs)
-  if [[ -z "$version" ]]; then
-    print_error "Could not determine version from setup.cfg."
-    exit 1
-  fi
-  # get the version from the package itself in $package_name/__version__.py
-  version_from_file=$(python -c "from $package_name.__version__ import __version__; print(__version__)")
-  echo "Version from file: $version_from_file"
-  if [[ "$version" != "$version_from_file" ]]; then
-    print_error "Version from setup.cfg($version) and __version__ ($version_from_file) do not match."
-    exit 1
-  fi
-  # we've got the version, now let's confirm with the user.
-  echo "Current version is $version."
-  echo ""
-
-  echo "Do you want to publish this version? (y/n)"
-  read -r response
-  if [[ "$response" != "y" ]]; then
-    echo "Exiting without publishing."
-    exit 1
-  fi
+get_package_name() {
+  echo "$(python -c 'import toml; print(toml.load("pyproject.toml")["project"]["name"])')"
 }
 
 check_if_published() {
-  if twine check dist/* | grep -q "$version"; then
-    print_error "Version $version is already published."
+  response=$(curl -s "https://pypi.org/pypi/$package_name/json")
+  if echo "$response" | grep -q "\"$version\""; then
+    print_error "Version $version is already published on PyPi."
     exit 1
   fi
 }
@@ -91,17 +62,35 @@ open_url_in_browser() {
 
 build_and_publish() {
   rm -rf dist
-  python setup.py sdist bdist_wheel && print_success "Package built successfully."
-  output=$(twine upload dist/*)
+  python -m build && print_success "Package built successfully." || exit 1
+  output=$(twine upload dist/* 2>&1)
+  if [ $? -ne 0 ]; then
+    print_error "Failed to upload package to PyPi."
+    echo "$output"
+    exit 1
+  fi
   print_success "Package published successfully."
   url=$(echo "$output" | grep -o 'https://pypi.org/project/[^ ]*' | sed 's/[^ ]*$/&/')
   echo "Package URL: $url"
 }
 
+confirm(){
+  echo "Building: $package_name: $version"
+  echo
+  read -p "Do you want to continue? [y/N] " -n 1 -r
+  if [[ ! $REPLY =~ ^[Yy]$ ]]; then
+    echo
+    echo "Aborted."
+    exit 1
+  fi
+}
 # no arguments, do everything.
 # if you want to do only one step, pass the argument , helpful for debugging.
 if [ "$1" = "" ]; then
-  get_version
+  package_name=$(get_package_name)
+  get_version "$package_name"
+  confirm
+  echo
   check_if_published
   create_and_push_git_tag
   build_and_publish
